name = "rolldoradocasino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradocasino.com.pt"
HMAC_KEY = "413e22bf5f8c15a109a0113127a9c53d2ef53c0108b8eeb6889f8eb81ed0c589"
COOKIE_NAME = "wte"
PLAY_PATH = "explore"
BUTTON_ID = "pf29ccc0fefdca07633fa6ec1e081b9a8"
GATE_SALT = "5f683bfc5ebd270e"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "hgrl"
CTA_SELECTOR = ".play-button"
